### ISSUE TITLE
Obtain Last seen time

### ISSUE THREAD

**Issue by boxgames1** [TelegramBot/Api#19]
Hi. Is there a way to get the last seen time (or "online") from a user?

I don't find any related method.

Thanks.

**Comment by iGusev** [comment]
In most cases, the bots react to external events (commands from users or other sources outside the telegram). It is not necessary for bots.

You can find [here (telegram-cli)](https://github.com/vysheng/tg) method , but it is not true way, because this library hacking telegram and provides ability to create bots via normal users accounts
